package constant

const (
	STATUS_CODE_GENERAL_SUCCESS  = "200"
	STATUS_CODE_GENERAL_ERROR    = "500"
	STATUS_CODE_VALIDATION_ERROR = "400"
	STATUS_CODE_PARSING_REQUEST  = "4001"


	HEADER_REQUEST_ID          = "X-Request-ID"
)
